apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fwdays-mailer
  namespace: fwdays-prod
spec:
  concurrencyPolicy: Forbid
  schedule: "* 4-19 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fwdays-backend
            image: %job-image-name%
            env:
            - name: SERVER_NAME
              valueFrom:
                secretKeyRef:
                  name: server-name
                  key: server-name
            envFrom:
            - configMapRef:
                name: backend-env
            args:
            - bash
            - -c
            - su www-data -c  "php bin/console stfalcon:mailer --host=fwdays.com --amount=45 --env=prod"
          restartPolicy: Never
          imagePullSecrets:
            - name: regcred-dockerhub
