doctrine:
    dbal:
        dbname: '%env(APP_DBNAME)%'
        host: '%env(APP_DBHOST)%'
        port: '%env(APP_DBPORT)%'
        user: '%env(APP_DBUSER)%'
        password: '%env(APP_DBPASS)%'
        driver: 'pdo_mysql'
        charset: 'utf8mb4'
#        url: 'pdo_mysql://%env(APP_DBUSER)%:%env(APP_DBPASS)%@%env(APP_DBHOST)%:%env(APP_DBPORT)%/%env(APP_DBNAME)%?charset=utf8mb4&serverVersion=5.6'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: false
            app:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/src/Entity"
                prefix: App\Entity\
                alias: App
        dql:
            datetime_functions:
                YEAR: DoctrineExtensions\Query\Mysql\Year
                MONTH: DoctrineExtensions\Query\Mysql\Month
                WEEK: DoctrineExtensions\Query\Mysql\Week
                DAY: DoctrineExtensions\Query\Mysql\Day
                DATE: DoctrineExtensions\Query\Mysql\Date