parameters:
    rss.title: "Frameworks Days"
    rss.description: "Новости событий, которые проходят под эгидой Frameworks Days"
    app.sponsor_image: "uploads/sponsors"
    app.speaker_image: "uploads/speakers"
    app.event_image: "uploads/events"
    app.event_header_video: "uploads/video"
    app.event_certificate: "uploads/certificate"
    app.upload_image: "uploads/images"
    app.media_cache: '/media/cache/'
    google_captcha_secret_key: '%env(GOOGLE_CAPTCHA_SECRET_KEY)%'
#    app.payment_system: '@App\Service\PaymentProcess\InterkassaService'
#    app.payment_system: 'App\Service\PaymentProcess\WayForPayService'
    app.config:
        wayforpay:
            shop_id: '%env(WAYFORPAY_SHOP_ID)%'
            secret: '%env(WAYFORPAY_SECRET)%'
        interkassa:
            shop_id: '%env(INTERKASSA_SHOP_ID)%'
            secret: '%env(INTERKASSA_SECRET)%'
        discount: 0.1

framework:
    router:
        utf8: true
#    assets:
#        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    #esi:             ~
    default_locale:  "%locale%"
    translator:
        default_path: '%kernel.project_dir%/translations'
    secret: '%env(APP_SECRET)%'
    form: true
    csrf_protection: true
    validation:
        enable_annotations: true
        email_validation_mode: html5
    templating:      { engines: ['twig'] }
    serializer:
        enabled: true
        enable_annotations: true
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
    workflows: null
    session:
        handler_id: snc_redis.session.handler

    cache:
        prefix_seed: fwdays
        app: cache.adapter.redis
        default_redis_provider: snc_redis.app_cache
        pools:
            doctrine.metadata_cache_pool:
                adapter: cache.adapter.redis
                provider: snc_redis.doctrine_metadata_cache
            doctrine.query_cache_pool:
                adapter: cache.adapter.redis
                provider: snc_redis.doctrine_query_cache
