services:

    App\EventListener\FOSUserEvents\UserProfileUpdateSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    App\EventListener\FOSUserEvents\UserRegistrationSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    App\EventListener\FOSUserEvents\UserResettingSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    App\EventListener\FOSUserEvents\UserChangePasswordSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    App\EventListener\Auth\UserAuthenticationSubscriber:
        tags:
            - { name: kernel.event_subscriber }