services:

    sonata.block.event.text:
        class: App\Service\SonataBlock\EventBlock\TextEventBlockService
        arguments: ['sonata.block.event.text', '@templating']
        tags: [name: 'sonata.block']

    sonata.block.event.youtube_private_video:
        class: App\Service\SonataBlock\EventBlock\EmbedPrivateVideoEventBlockService
        arguments: ['sonata.block.event.text', '@templating', '@App\Service\User\UserService', '@App\Repository\TicketRepository', '@App\Repository\UserEventRegistrationRepository']
        tags: [name: 'sonata.block']

    sonata.block.event.youtube_private_playlist:
        class: App\Service\SonataBlock\EventBlock\EmbedPrivateVideoEventBlockService
        arguments: ['sonata.block.event.text', '@templating', '@App\Service\User\UserService', '@App\Repository\TicketRepository', '@App\Repository\UserEventRegistrationRepository']
        calls:
            - [setIsPlayList, ['true']]
        tags: [name: 'sonata.block']

    sonata.block.event.vimeo_private_video:
        class: App\Service\SonataBlock\EventBlock\EmbedPrivateVideoEventBlockService
        arguments: ['sonata.block.event.text', '@templating', '@App\Service\User\UserService', '@App\Repository\TicketRepository', '@App\Repository\UserEventRegistrationRepository']
        calls:
            - [setTemplate, ['Redesign/Event/event.vimeo_video_block.html.twig']]
        tags: [name: 'sonata.block']

    sonata.block.event.vimeo_private_playlist:
        class: App\Service\SonataBlock\EventBlock\EmbedPrivateVideoEventBlockService
        arguments: ['sonata.block.event.text', '@templating', '@App\Service\User\UserService', '@App\Repository\TicketRepository', '@App\Repository\UserEventRegistrationRepository']
        calls:
            - [setIsPlayList, ['true']]
            - [setTemplate, ['Redesign/Event/event.vimeo_video_block.html.twig']]
        tags: [name: 'sonata.block']

    sonata.block.event.partners:
        class: App\Service\SonataBlock\EventBlock\PartnersEventBlockService
        arguments: ['sonata.block.event.partners', '@templating', '@App\Repository\SponsorRepository', '@App\Repository\CategoryRepository']
        tags: [name: 'sonata.block']

    sonata.block.event.prices:
        class: App\Service\SonataBlock\EventBlock\PricesEventBlockService
        arguments: ['sonata.block.event.prices', '@templating', '@App\Repository\TicketCostRepository']
        tags: [name: 'sonata.block']

    sonata.block.event.description:
        class: App\Service\SonataBlock\EventBlock\DescriptionEventBlockService
        arguments: ['sonata.block.event.description', '@templating']
        tags: [name: 'sonata.block']

    sonata.block.event.venue:
        class: App\Service\SonataBlock\EventBlock\VenueEventBlockService
        arguments: ['sonata.block.event.venue', '@templating', '@App\Service\EventService']
        tags: [name: 'sonata.block']

    sonata.block.event.program:
        class: App\Service\SonataBlock\EventBlock\ProgramEventBlockService
        arguments: ['sonata.block.event.program', '@templating', '@App\Service\EventService']
        tags: [name: 'sonata.block']

    sonata.block.event.speakers:
        class: App\Service\SonataBlock\EventBlock\SpeakersEventBlockService
        arguments: ['sonata.block.event.speakers', '@templating', '@translator', '@App\Repository\ReviewRepository']
        tags: [name: 'sonata.block']

    sonata.block.event.reviews:
        class: App\Service\SonataBlock\EventBlock\ReviewsEventBlockService
        arguments: ['sonata.block.event.reviews', '@templating', '@App\Repository\ReviewRepository']
        tags: [name: 'sonata.block']

    sonata.block.event.candidate_speakers:
        class: App\Service\SonataBlock\EventBlock\CandidateSpeakersEventBlockService
        arguments: ['sonata.block.event.candidate_speakers', '@templating', '@translator', '@App\Repository\ReviewRepository']
        tags: [name: 'sonata.block']

    sonata.block.event.committee_speakers:
        class: App\Service\SonataBlock\EventBlock\CommitteeSpeakersEventBlockService
        arguments: ['sonata.block.event.committee_speakers', '@templating', '@translator']
        tags: [name: 'sonata.block']

    sonata.block.event.expert_speakers:
        class: App\Service\SonataBlock\EventBlock\DiscussionExpertsEventBlockService
        arguments: ['sonata.block.event.expert_speakers', '@templating', '@translator']
        tags: [name: 'sonata.block']

    sonata.block.event.ticket_status:
        class: App\Service\SonataBlock\EventBlock\TicketStatusEventBlockService
        arguments: ['sonata.block.event.ticket_status', '@templating', '@App\Service\Ticket\TicketService']
        tags: [name: 'sonata.block']

    sonata.block.footer:
        class: App\Service\SonataBlock\FooterBlockService
        arguments: ['sonata.block.footer', '@templating', '@App\Repository\PageRepository']
        tags: [name: 'sonata.block']

    sonata.block.language_switcher:
        class: App\Service\SonataBlock\LanguageSwitcherBlockService
        arguments: ['sonata.block.language_switcher', '@templating', '@request_stack', '%locales%']
        tags: [name: 'sonata.block']

    sonata.block.email_user_subscribe:
        class: App\Service\SonataBlock\EmailSubscribeBlockService
        arguments: ['sonata.block.language_switcher', '@templating']
        calls:
            - [setEmailHashValidationService, ['@App\Service\EmailHashValidationService']]
        tags: [name: 'sonata.block']

    sonata.block.service.statistic:
        class: App\Service\SonataBlock\StatisticBlockService
        arguments: ['sonata.block.service.statistic', '@templating']
        tags:
            - { name: sonata.block }