services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    sonata.block.event.text:
        class: App\Service\SonataBlock\EventBlock\TextEventBlockService
        arguments: ['@twig']
        tags: [name: 'sonata.block']

    sonata.block.event.youtube_private_video:
        class: App\Service\SonataBlock\EventBlock\EmbedPrivateVideoEventBlockService
        arguments:
            - '@twig'
            - '@App\Service\User\UserService'
            - '@App\Service\Ticket\TicketService'
            - '@App\Service\VideoAccess\GrandAccessVideoService'
            - '@App\Repository\UserEventRegistrationRepository'
        calls:
            - [ setGrandAccessType, [ !php/const App\Service\VideoAccess\GrandAccessVideoService::REGISTERED_FOR_EVENT_AND_HAVE_NOT_ANY_TICKET ] ]
        tags: [name: 'sonata.block']

    sonata.block.event.youtube_private_playlist:
        class: App\Service\SonataBlock\EventBlock\EmbedPrivateVideoEventBlockService
        arguments:
            - '@twig'
            - '@App\Service\User\UserService'
            - '@App\Service\Ticket\TicketService'
            - '@App\Service\VideoAccess\GrandAccessVideoService'
            - '@App\Repository\UserEventRegistrationRepository'
        calls:
            - [setIsPlayList, ['true']]
            - [setGrandAccessType, [!php/const App\Service\VideoAccess\GrandAccessVideoService::REGISTERED_FOR_EVENT_AND_HAVE_NOT_ANY_TICKET]]
        tags: [name: 'sonata.block']

    sonata.block.event.vimeo_private_video:
        class: App\Service\SonataBlock\EventBlock\EmbedPrivateVideoEventBlockService
        arguments:
            - '@twig'
            - '@App\Service\User\UserService'
            - '@App\Service\Ticket\TicketService'
            - '@App\Service\VideoAccess\GrandAccessVideoService'
            - '@App\Repository\UserEventRegistrationRepository'
        calls:
            - [setTemplate, ['Redesign/Event/event.vimeo_video_block.html.twig']]
            - [setGrandAccessType, [!php/const App\Service\VideoAccess\GrandAccessVideoService::REGISTERED_FOR_EVENT_AND_HAVE_NOT_ANY_TICKET]]
        tags: [name: 'sonata.block']

    sonata.block.event.vimeo_private_playlist:
        class: App\Service\SonataBlock\EventBlock\EmbedPrivateVideoEventBlockService
        arguments:
            - '@twig'
            - '@App\Service\User\UserService'
            - '@App\Service\Ticket\TicketService'
            - '@App\Service\VideoAccess\GrandAccessVideoService'
            - '@App\Repository\UserEventRegistrationRepository'
        calls:
            - [setIsPlayList, ['true']]
            - [setTemplate, ['Redesign/Event/event.vimeo_video_block.html.twig']]
            - [setGrandAccessType, [!php/const App\Service\VideoAccess\GrandAccessVideoService::REGISTERED_FOR_EVENT_AND_HAVE_NOT_ANY_TICKET]]
        tags: [name: 'sonata.block']

    sonata.block.event.youtube_private_video_standard:
        class: App\Service\SonataBlock\EventBlock\EmbedPrivateVideoEventBlockService
        arguments:
            - '@twig'
            - '@App\Service\User\UserService'
            - '@App\Service\Ticket\TicketService'
            - '@App\Service\VideoAccess\GrandAccessVideoService'
            - '@App\Repository\UserEventRegistrationRepository'
        calls:
            - [ setGrandAccessType, [ !php/const App\Service\VideoAccess\GrandAccessVideoService::BOUGHT_STANDARD_TICKET ] ]
        tags: [name: 'sonata.block']

    sonata.block.event.youtube_private_playlist_standard:
        class: App\Service\SonataBlock\EventBlock\EmbedPrivateVideoEventBlockService
        arguments:
            - '@twig'
            - '@App\Service\User\UserService'
            - '@App\Service\Ticket\TicketService'
            - '@App\Service\VideoAccess\GrandAccessVideoService'
            - '@App\Repository\UserEventRegistrationRepository'
        calls:
            - [setIsPlayList, ['true']]
            - [setGrandAccessType, [!php/const App\Service\VideoAccess\GrandAccessVideoService::BOUGHT_STANDARD_TICKET]]
        tags: [name: 'sonata.block']

    sonata.block.event.vimeo_private_video_standard:
        class: App\Service\SonataBlock\EventBlock\EmbedPrivateVideoEventBlockService
        arguments:
            - '@twig'
            - '@App\Service\User\UserService'
            - '@App\Service\Ticket\TicketService'
            - '@App\Service\VideoAccess\GrandAccessVideoService'
            - '@App\Repository\UserEventRegistrationRepository'
        calls:
            - [setTemplate, ['Redesign/Event/event.vimeo_video_block.html.twig']]
            - [setGrandAccessType, [!php/const App\Service\VideoAccess\GrandAccessVideoService::BOUGHT_STANDARD_TICKET]]
        tags: [name: 'sonata.block']

    sonata.block.event.vimeo_private_playlist_standard:
        class: App\Service\SonataBlock\EventBlock\EmbedPrivateVideoEventBlockService
        arguments:
            - '@twig'
            - '@App\Service\User\UserService'
            - '@App\Service\Ticket\TicketService'
            - '@App\Service\VideoAccess\GrandAccessVideoService'
            - '@App\Repository\UserEventRegistrationRepository'
        calls:
            - [setIsPlayList, ['true']]
            - [setTemplate, ['Redesign/Event/event.vimeo_video_block.html.twig']]
            - [setGrandAccessType, [!php/const App\Service\VideoAccess\GrandAccessVideoService::BOUGHT_STANDARD_TICKET]]
        tags: [name: 'sonata.block']

    sonata.block.event.youtube_private_video_premium:
        class: App\Service\SonataBlock\EventBlock\EmbedPrivateVideoEventBlockService
        arguments:
            - '@twig'
            - '@App\Service\User\UserService'
            - '@App\Service\Ticket\TicketService'
            - '@App\Service\VideoAccess\GrandAccessVideoService'
            - '@App\Repository\UserEventRegistrationRepository'
        calls:
            - [ setGrandAccessType, [ !php/const App\Service\VideoAccess\GrandAccessVideoService::BOUGHT_PREMIUM_TICKET ] ]
        tags: [name: 'sonata.block']

    sonata.block.event.youtube_private_playlist_premium:
        class: App\Service\SonataBlock\EventBlock\EmbedPrivateVideoEventBlockService
        arguments:
            - '@twig'
            - '@App\Service\User\UserService'
            - '@App\Service\Ticket\TicketService'
            - '@App\Service\VideoAccess\GrandAccessVideoService'
            - '@App\Repository\UserEventRegistrationRepository'
        calls:
            - [setIsPlayList, ['true']]
            - [setGrandAccessType, [!php/const App\Service\VideoAccess\GrandAccessVideoService::BOUGHT_PREMIUM_TICKET]]
        tags: [name: 'sonata.block']

    sonata.block.event.vimeo_private_video_premium:
        class: App\Service\SonataBlock\EventBlock\EmbedPrivateVideoEventBlockService
        arguments:
            - '@twig'
            - '@App\Service\User\UserService'
            - '@App\Service\Ticket\TicketService'
            - '@App\Service\VideoAccess\GrandAccessVideoService'
            - '@App\Repository\UserEventRegistrationRepository'
        calls:
            - [setTemplate, ['Redesign/Event/event.vimeo_video_block.html.twig']]
            - [setGrandAccessType, [!php/const App\Service\VideoAccess\GrandAccessVideoService::BOUGHT_PREMIUM_TICKET]]
        tags: [name: 'sonata.block']

    sonata.block.event.vimeo_private_playlist_premium:
        class: App\Service\SonataBlock\EventBlock\EmbedPrivateVideoEventBlockService
        arguments:
            - '@twig'
            - '@App\Service\User\UserService'
            - '@App\Service\Ticket\TicketService'
            - '@App\Service\VideoAccess\GrandAccessVideoService'
            - '@App\Repository\UserEventRegistrationRepository'
        calls:
            - [setIsPlayList, ['true']]
            - [setTemplate, ['Redesign/Event/event.vimeo_video_block.html.twig']]
            - [setGrandAccessType, [!php/const App\Service\VideoAccess\GrandAccessVideoService::BOUGHT_PREMIUM_TICKET]]
        tags: [name: 'sonata.block']

    sonata.block.event.partners:
        class: App\Service\SonataBlock\EventBlock\PartnersEventBlockService
        arguments: ['@twig', '@App\Repository\SponsorRepository', '@App\Repository\CategoryRepository']
        tags: [name: 'sonata.block']

    sonata.block.event.prices:
        class: App\Service\SonataBlock\EventBlock\PricesEventBlockService
        arguments: ['@twig', '@App\Repository\TicketCostRepository']
        tags: [name: 'sonata.block']

    sonata.block.event.description:
        class: App\Service\SonataBlock\EventBlock\DescriptionEventBlockService
        arguments: ['@twig']
        tags: [name: 'sonata.block']

    sonata.block.event.venue:
        class: App\Service\SonataBlock\EventBlock\VenueEventBlockService
        arguments: ['@twig', '@App\Service\EventService']
        tags: [name: 'sonata.block']

    sonata.block.event.program:
        class: App\Service\SonataBlock\EventBlock\ProgramEventBlockService
        arguments: ['@twig', '@App\Service\EventService']
        tags: [name: 'sonata.block']

    sonata.block.event.speakers:
        class: App\Service\SonataBlock\EventBlock\SpeakersEventBlockService
        arguments: ['@twig', '@App\Repository\ReviewRepository']
        tags: [name: 'sonata.block']

    sonata.block.event.reviews:
        class: App\Service\SonataBlock\EventBlock\ReviewsEventBlockService
        arguments: ['@twig', '@App\Repository\ReviewRepository']
        tags: [name: 'sonata.block']

    sonata.block.event.candidate_speakers:
        class: App\Service\SonataBlock\EventBlock\CandidateSpeakersEventBlockService
        arguments: ['@twig', '@App\Repository\ReviewRepository']
        tags: [name: 'sonata.block']

    sonata.block.event.committee_speakers:
        class: App\Service\SonataBlock\EventBlock\CommitteeSpeakersEventBlockService
        arguments: ['@twig']
        tags: [name: 'sonata.block']

    sonata.block.event.expert_speakers:
        class: App\Service\SonataBlock\EventBlock\DiscussionExpertsEventBlockService
        arguments: ['@twig']
        tags: [name: 'sonata.block']

    sonata.block.event.ticket_status:
        class: App\Service\SonataBlock\TicketStatusEventBlockService
        arguments: ['@twig', '@App\Service\Ticket\TicketService']
        tags: [name: 'sonata.block']

    sonata.block.footer:
        class: App\Service\SonataBlock\FooterBlockService
        arguments: ['@twig', '@App\Repository\PageRepository']
        tags: [name: 'sonata.block']

    sonata.block.banner:
        class: App\Service\SonataBlock\BannerBlockService
        tags: [name: 'sonata.block']

    sonata.block.language_switcher:
        class: App\Service\SonataBlock\LanguageSwitcherBlockService
        arguments: ['@twig', '@request_stack', '%locales%']
        tags: [name: 'sonata.block']

    sonata.block.email_user_subscribe:
        class: App\Service\SonataBlock\EmailSubscribeBlockService
        arguments: ['@twig']
        calls:
            - [setEmailHashValidationService, ['@App\Service\EmailHashValidationService']]
        tags: [name: 'sonata.block']

    sonata.block.service.statistic:
        class: App\Service\SonataBlock\StatisticBlockService
        arguments: ['@twig']
        tags: [name: 'sonata.block']

    sonata.block.event.entity_referer:
        class: App\Service\SonataBlock\AdminBlock\PaymentRefererBlockService
        arguments: ['@twig', '@App\Repository\Referer\RefererRepository']
        tags: [name: 'sonata.block']