image: jekakm/php71-core:201901222
cache:
    paths:
        - vendor/

before_script:
    - sudo chown -R www-data:www-data /var/www
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install

stages:
    - 'CI jobs'
    - 'SonarQube'

sonar-scanner:
    image: black15/php71-core-sonar:201807162
    stage: 'SonarQube'
    only:
        - master
        - develop
    script:
        - sudo sonar-scanner -Dsonar.projectKey=fwdays -Dsonar.sources=. -Dsonar.host.url=https://sonar.stfalcon.com -Dsonar.login=$SONAR_TOKEN