build:
  tests:
    override:
      - bin/phpunit -c app
  environment:
    rabbitmq: false
    mysql: 5.6
    postgresql: false
    mongodb: false
    elasticsearch: false
    redis: false
    memcached: false
    neo4j: false
    php:
      version: 5.4
  services:
    mysql: 5.6
  dependencies:
    before:
      - mysql -u root -e "CREATE DATABASE IF NOT EXISTS fwdays_com_development"
  project_setup:
    before:
      - mysql -u root -e "CREATE DATABASE IF NOT EXISTS fwdays_com_test"

before_commands:
  - 'composer install --prefer-source'

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths:
    - src/*
  excluded_paths:
    - vendor/*

tools:
  php_code_sniffer:
    config:
      standard: "PSR2"
  php_cs_fixer: true
  sensiolabs_security_checker: true
