build:
  nodes:
    tests:
      dependencies:
        override:
          - mysql -u root -e "CREATE DATABASE IF NOT EXISTS fwdays_com_test"
          - composer install --ignore-platform-reqs --no-interaction --no-scripts
  tests:
    override:
      - bin/phpunit -c app
  environment:
    rabbitmq: false
    mysql: 5.6
    postgresql: false
    mongodb: false
    elasticsearch: false
    redis: false
    memcached: false
    neo4j: false
    php:
      version: 5.4
  services:
    mysql: 5.6

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths:
    - src/*
  excluded_paths:
    - vendor/*

tools:
  php_code_sniffer:
    config:
      standard: "PSR2"
  php_cs_fixer: true
  sensiolabs_security_checker: true
