before_commands:
  - "composer install --prefer-source"

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths:
    - src/*
  excluded_paths:
    - vendor/*
    - tests/*

tools:
  php_code_sniffer:
    config:
      standard: "PSR2"
  php_cs_fixer: true
  sensiolabs_security_checker: true
