build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - phpcs-run -p src/ tests/ --ignore=tests/perf.php,tests/coverage --extensions=php
          - php-scrutinizer-run --disable-security-analysis
  cache:
    directories:
      - ~/.composer   # Composer home directory (avoid fetching already fetched packages)
      # vendor is already included.

  environment:
    rabbitmq: false
    mysql: false
    postgresql: false
    mongodb: false
    elasticsearch: false
    redis: false
    memcached: false
    neo4j: false
    php:
      version: 5.4

  dependencies:
    override:
      - composer install --no-interaction

before_commands:
  - 'composer install --prefer-source'

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths:
    - src/*
  excluded_paths:
    - vendor/*

tools:
  php_code_sniffer:
    config:
      standard: "PSR2"
  php_cs_fixer: true
  sensiolabs_security_checker: true
