build:
  nodes:
    tests:
      services:
        mysql: 5.6
      dependencies:
        override:
#          - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS fwdays_com_test"
#          - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS fwdays_com_development"
#          - composer install --no-interaction
          - true
  tests:
    override:
#      - bin/phpunit -c app
      - true
  environment:
    rabbitmq: false
    mysql: 5.6
    postgresql: false
    mongodb: false
    elasticsearch: false
    redis: false
    memcached: false
    neo4j: false
    php:
      version: 5.4

checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - 'app/*'
    - 'bin/*'
    - '*.min.js'
    - 'web/assets/*'

coding_style:
  php: {  }

tools:
  php_code_sniffer:
    config:
      standard: "PSR2"
  php_cs_fixer: true
  sensiolabs_security_checker: true
