build:
  environment:
    php:
      version: '5.4'
  nodes:
    composer:
      dependencies:
        before:
          - sudo service start mysql || true
          - mysql -e "CREATE DATABASE fwdays_com_development"

before_commands:
  - 'composer install --prefer-source'

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths:
    - src/*
  excluded_paths:
    - vendor/*

tools:
  php_code_sniffer:
    config:
      standard: "PSR2"
  php_cs_fixer: true
  sensiolabs_security_checker: true
