build:
  nodes:
    analysis:
      tests:
        before:
          - mysql -e "CREATE DATABASE IF NOT EXISTS fwdays_com_development"
          - mysql -e "CREATE DATABASE IF NOT EXISTS fwdays_com_test"
        override:
          - phpcs-run -p src/*/*Bundle/Tests src/*/Bundle/*Bundle/Tests --extensions=php
          - php-scrutinizer-run --disable-security-analysis
  cache:
    directories:
      - ~/.composer   # Composer home directory (avoid fetching already fetched packages)
      # vendor is already included.

  environment:
    rabbitmq: false
    mysql: 5.5
    postgresql: false
    mongodb: false
    elasticsearch: false
    redis: false
    memcached: false
    neo4j: false
    php:
      version: 5.4
  services:
    mysql: 5.5
  dependencies:
    before:
      - mysql -e "CREATE DATABASE IF NOT EXISTS fwdays_com_development"
  project_setup:
    before:
      - mysql -e "CREATE DATABASE IF NOT EXISTS fwdays_com_test"

before_commands:
  - 'composer install --prefer-source'

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths:
    - src/*
  excluded_paths:
    - vendor/*

tools:
  php_code_sniffer:
    config:
      standard: "PSR2"
  php_cs_fixer: true
  sensiolabs_security_checker: true
