build:
  nodes:
    tests:
      services:
        mysql: 5.5
      dependencies:
        override:
          - composer install --no-interaction --no-scripts
          - php vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/bin/build_bootstrap.php
          - php app/console do:da:cr --env=test
          - php app/console do:mi:mi --no-interaction --env=test
          - php app/console do:fi:lo --no-interaction --env=test
          - wget https://files-cdn.liferay.com/mirrors/geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.xz -O geodata/GeoLiteCity.dat.xz
          - unxz geodata/GeoLiteCity.dat.xz
  tests:
    stop_on_failure: false
    override:
      - bin/phpunit -c app

  environment:
    rabbitmq: false
    mysql: 5.5
    postgresql: false
    mongodb: false
    elasticsearch: false
    redis: false
    memcached: false
    neo4j: false
    php:
      version: 5.4

checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - 'app/*'
    - 'bin/*'
    - '*.min.js'
    - 'web/assets/*'

coding_style:
  php: {  }

tools:
  php_code_sniffer:
    config:
      standard: "PSR2"
  php_cs_fixer: true
  sensiolabs_security_checker: true
