version: '2'

services:
   db:
     image: mysql:5.6
     volumes:
       - db_data:/var/lib/mysql
       - ./docker-files/mysql-conf.d:/etc/mysql/conf.d
     environment:
       MYSQL_ROOT_PASSWORD: qwerty
   mailcatcher:
     image: juliolustosa/mailcatcher
     ports:
       - "1026:1025"
       - "1081:1080"
   fwdays:
     depends_on:
       - db
       - mailcatcher
     build: .
     volumes:
       - .:/var/www/html
     ports:
       - "8000:80"
       - "9999:9000"
volumes:
    db_data:
