version: '3'
services:
    nginx:
        image: jekakm/nginx-core:201802261
        ports:
            - "127.0.0.1:8000:80"
        volumes:
            - "./docker-configs/fwdays-dev/nginx.conf:/etc/nginx/sites-enabled/default"
            - ".:/app:cached"
        depends_on:
            - "php"

    php:
        image: gitlab.stfalcon.com:4567/stfalcon/fwdays/fwdays-dev:v1
        environment:
            - "PHP_IDE_CONFIG=serverName=fwdays-docker"
        volumes:
            - "./docker-configs/fwdays-dev/php-fpm.ini:/etc/php/7.1/fpm/php.ini"
            - "./docker-configs/fwdays-dev/php-cli.ini:/etc/php/7.1/cli/php.ini"
            - ".:/app:cached"
            - "composer:/var/www/.composer"
        depends_on:
            - "mysql"
            - "mailcatcher"
            - "sessions"

    php_cli:
        build:
            context: ./docker-configs/fwdays-dev-cli
        environment:
            - "PHP_IDE_CONFIG=serverName=fwdays-docker"
        volumes:
            - "./docker-configs/fwdays-dev/php-cli.ini:/etc/php/7.1/cli/php.ini"
            - "./docker-configs/fwdays-dev/xdebug.ini:/etc/php/7.1/mods-available/xdebug.ini"
            - ".:/app:cached"
            - "composer:/var/www/.composer"

    mysql:
        image: gitlab.stfalcon.com:4567/stfalcon/fwdays/fwdays-mysql:v2
        volumes:
            - "mysqldata:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: qwerty
        ports:
            - "127.0.0.1:13306:3306"

    mailcatcher:
        image: jekakm/mailcatcher:201803011
        ports:
            - "127.0.0.1:1080:1080"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: qwerty
        ports:
            - "127.0.0.1:6789:80"
        depends_on:
            - "mysql"

    sessions:
        image: redis:5.0.4

    minio:
        image: minio/minio:latest
        hostname: minio
        container_name: minio
        command: server /data
        volumes:
            - "minio:/data"
        ports:
            - "127.0.0.1:9001:9000"
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: qwe12345

    createbuckets:
        image: minio/mc
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc config host add minio http://minio:9000 minio qwe12345;
            /usr/bin/mc mb minio/fwdays;
            exit 0;
            "

volumes:
    mysqldata:
    composer:
    minio: