version: '3'
services:
    nginx:
        image: nginx:1.17.0
        ports:
            - "127.0.0.1:8000:80"
        volumes:
            - "./docker-configs/fwdays-dev/configs/nginx.conf:/etc/nginx/conf.d/default.conf"
            - ".:/app:cached"
        depends_on:
            - "php"

    minio-public:
        image: nginx:1.17.0
        ports:
            - "127.0.0.1:8001:80"
        volumes:
            - "./docker-configs/fwdays-dev/configs/nginx-minio.conf:/etc/nginx/conf.d/default.conf"
            - "minio:/data"
        depends_on:
            - "php"

    php:
        image: gitlab.stfalcon.com:4567/stfalcon/fwdays/fwdays-dev:v1.1
        environment:
            - "PHP_IDE_CONFIG=serverName=fwdays-docker"
        volumes:
            - "./docker-configs/fwdays-dev/configs/php-fpm.ini:/etc/php/7.3/fpm/php.ini"
            - "./docker-configs/fwdays-dev/configs/php-cli.ini:/etc/php/7.3/cli/php.ini"
            - ".:/app:cached"
            - "composer:/var/www/.composer"
            - "bash-history-user:/var/www/history/"
            - "bash-history-root:/root/history/"
        depends_on:
            - "mysql"
            - "mailcatcher"
            - "sessions"

    php_cli:
        build:
            context: ./docker-configs/fwdays-dev-cli
        environment:
            - "PHP_IDE_CONFIG=serverName=fwdays-docker"
        volumes:
            - "./docker-configs/fwdays-dev/configs/php-fpm.ini:/etc/php/7.3/fpm/php.ini"
            - "./docker-configs/fwdays-dev/configs/php-cli.ini:/etc/php/7.3/cli/php.ini"
            - "./docker-configs/fwdays-dev/configs/xdebug.ini:/etc/php/7.3/mods-available/xdebug.ini"
            - ".:/app:cached"
            - "composer:/var/www/.composer"
            - "bash-history-user:/var/www/history/"
            - "bash-history-root:/root/history/"
        depends_on:
            - "mysql"
            - "mailcatcher"
            - "sessions"

    mysql:
        image: gitlab.stfalcon.com:4567/stfalcon/fwdays/fwdays-mysql:v3
        volumes:
            - "mysqldata:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: qwerty
        ports:
            - "127.0.0.1:13306:3306"

    mailcatcher:
        image: jekakm/mailcatcher:201803011
        ports:
            - "127.0.0.1:1080:1080"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: qwerty
        ports:
            - "127.0.0.1:6789:80"
        depends_on:
            - "mysql"

    sessions:
        image: redis:5.0.4

    minio:
        image: minio/minio:latest
        hostname: minio
        container_name: minio
        command: server /data
        volumes:
            - "minio:/data"
        ports:
            - "127.0.0.1:9001:9000"
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: qwe12345

    createbuckets:
        image: minio/mc
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc config host add minio http://minio:9000 minio qwe12345;
            /usr/bin/mc mb minio/fwdays;
            exit 0;
            "

volumes:
    mysqldata:
    composer:
    minio:
    bash-history-user:
    bash-history-root: