#!/bin/bash

cd /app
cp app/config/parameters.yml.docker app/config/parameters.yml
mysql -u root -pqwerty -h mysql -e "CREATE DATABASE IF NOT EXISTS fwdays_com_development"
composer.phar install
php bin/console do:mi:mi --no-interaction
php bin/console do:fi:lo --no-interaction
php bin/console assets:install web --symlink
php bin/console assetic:dump
php bin/console lexik:translations:import
unxz geodata/GeoLiteCity.dat.xz
npm install
npm run gulp-dev
