admin_area:
    resource: '../../src/Resources/config/sonata_admin.xml'
    prefix: /admin
    defaults: { _locale: uk}
    options:
        i18n: false

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    defaults: { _locale: uk}
    options:
        i18n: false

sonata_admin_ticket_check:
    path:  /admin/ticket/check
    defaults: { _controller: App\Controller\TicketAdminController:checkAction }
    options:
        i18n: false

admin_show_statistic:
    path:  /admin/statistic
    defaults:
        _controller: App\Controller\AdminController:showStatisticAction
        _locale: uk
    options:
        i18n: false

admin_show_event_statistic:
    path:  /admin/event_statistic
    defaults:
        _controller: App\Controller\AdminController:showEventStatisticAction
        _locale: uk
    options:
        i18n: false