<?php

namespace App\Repository;

use App\Entity\Event;
use App\Entity\Speaker;
use Doctrine\ORM\EntityRepository;

/**
 * ReviewRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository
{
    /**
     * Find reviews of speaker for event.
     *
     * @param Speaker $speaker
     * @param Event   $event
     *
     * @return array
     */
    public function findReviewsOfSpeakerForEvent(Speaker $speaker, Event $event)
    {
        return $this->createQueryBuilder('r')
            ->join('r.speakers', 's')
            ->where('s.id = :speaker')
            ->andWhere('r.event = :event')
            ->setParameter('speaker', $speaker)
            ->setParameter('event', $event)
            ->getQuery()
            ->execute();
    }

    /**
     * @param Event $event
     *
     * @return array
     */
    public function findReviewsByEvent(Event $event)
    {
        $qb = $this->createQueryBuilder('r');

        $qb->where($qb->expr()->eq('r.event', ':event'))
            ->setParameter('event', $event);

        return $qb->getQuery()->getResult();
    }
}
