liip_imagine:
  loaders:
    default:
      filesystem:
        locator: filesystem_insecure
  filter_sets:
    cache: ~
    speaker_size:
      filters:
        relative_resize: { widen: 232 }
        crop: { size: [ 232, 232 ], start: [ 0, 0 ] }