#_assetic:
#    resource: .
#    type:     assetic

#_configurator:
#    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
#    prefix:   /_configurator

#_main:
#    resource: routing.yml
#    type: be_simple_i18n