liip_imagine:
  resolvers:
    images:
      aws_s3:
        client_config:
          credentials:
            key:    '%aws_access_key_id%'
            secret: '%aws_secret_access_key%'
          version: 'latest'
          region: '%aws_region%'
          endpoint: '%aws_endpoint%'
        bucket: "%aws_s3_bucketname%"
        get_options:
          Scheme: https
        put_options:
          CacheControl: "max-age=86400"
  cache: images
  filter_sets:
    speaker:
      filters:
        relative_resize: { widen: 232 }
        crop: { size: [ 232, 232 ], start: [ 0, 0 ] }
