imports:
    - { resource: config.yml }

parameters:
    app.sponsor_image: "%kernel.environment%/uploads/sponsors"
    app.speaker_image: "%kernel.environment%/uploads/speakers"
    app.event_image: "%kernel.environment%/uploads/events"
    app.upload_image: "%kernel.environment%/uploads/images"

doctrine:
    dbal:
        server_version: 5.6

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true

#swiftmailer:
#    transport: mail
#    host:      localhost


twig:
    globals:
        fb_page_id: "349461782222519"
        sentry_dsn_js_public: "%sentry_dsn_js_public%"

#parameters:
#     graylog.hostname: localhost
#     graylog.port: 12201

services:
    app.assets.s3:
        class: Aws\S3\S3Client
        arguments:
            -
                version: 'latest'
                region: '%aws_region%'
                endpoint: '%aws_endpoint%'
                use_path_style_endpoint: true
                credentials:
                    key: '%aws_access_key_id%'
                    secret: '%aws_secret_access_key%'