parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: fwdays_com_development
    database_user: root
    database_password: ~

    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: ~
    mailer_password: ~
    mailer_port: 25

    locale: uk
    locales: [uk, ru, en]

    secret: "012ZLNrkD4GbnlfNyzGb#HEM`m8]uX.J"
    google_captcha_secret_key: your_captcha_secret_key
    google_captcha_site_key: your_captcha_site_key

    interkassa_secret: "8GLHlDz1QzpYLduP"
    interkassa_secret_test: "BQHpiDLt4efYBFQs"
    tracking_id: "UA-19310691-2"

    mandrill_api_key: your_api_key