imports:
    - { resource: "@ApplicationDefaultBundle/Resources/config/admin.yml" }
    - { resource: "@ApplicationDefaultBundle/Resources/config/services.yml" }

services:
    monolog.processor.added_host:
        class: Monolog\Processor\WebProcessor
        tags:
            - { name: monolog.processor, method: __invoke }

    app.prepare_file_storage:
        class: Application\Bundle\DefaultBundle\DataFixtures\PrepareFileStorage
        arguments:
            - '%kernel.environment%'
            -
                - '@oneup_flysystem.sponsor_image_filesystem'
                - '@oneup_flysystem.speaker_photo_filesystem'
                - '@oneup_flysystem.event_image_filesystem'
                - '@oneup_flysystem.upload_image_filesystem'

    Application\Bundle\DefaultBundle\DataFixtures\ORM\:
        resource: '../../src/Application/Bundle/DefaultBundle/DataFixtures/ORM/*'
        tags: ['doctrine.fixture.orm']