snc_redis:
    clients:
        session:
            dsn: "%redis_session_url%"
            type: predis
            logging: '%kernel.debug%'
            alias: session

    session:
        client: session
        ttl: 1728000
        prefix: session_prefix_
