vich_uploader:
  db_driver: orm
  storage: flysystem
  mappings:
    sponsor_image:
      uri_prefix: '%app.sponsor_image%'
      upload_destination: sponsor_image
    speaker_photo:
      uri_prefix: '%app.speaker_image%'
      upload_destination: speaker_photo
      delete_on_update: true
    event_image:
      uri_prefix: '%app.event_image%'
      upload_destination: event_image