framework:
    profiler: { only_exceptions: false }

parameters:
    app.sponsor_image: "%kernel.environment%/uploads/sponsors"
    app.speaker_image: "%kernel.environment%/uploads/speakers"
    app.event_image: "%kernel.environment%/uploads/events"
    app.upload_image: "%kernel.environment%/uploads/images"