<?php

namespace Stfalcon\Bundle\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Application\Bundle\UserBundle\Entity\User;
use Stfalcon\Bundle\EventBundle\Entity\Event;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{

    /**
     * User involved in an event
     *
     * @param User $user
     * @param Event $event
     *
     * @return boolean
     */
    public function isActiveEventForUser(Event $event, User $user)
    {
        return (bool)$this->getEntityManager()
            ->createQuery('
                SELECT COUNT(t.id)
                FROM StfalconEventBundle:Ticket t
                JOIN t.event e
                WHERE e.active = TRUE
                    AND t.user = :user
                    AND t.event = :event
            ')
            ->setParameter('event', $event)
            ->setParameter('user', $user)
            ->getSingleScalarResult();
    }
}