<?php

namespace Stfalcon\Bundle\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Application\Bundle\UserBundle\Entity\User;
use Stfalcon\Bundle\EventBundle\Entity\Event;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralNewsRepository extends EntityRepository
{
    /**
     * Get array of last news
     *
     * @param integer $count
     * @return array
     */
    public function getLastNews($count = null)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                    SELECT 
                        n
                    FROM 
                        StfalconEventBundle:GeneralNews n
                    ORDER BY 
                        n.created_at DESC
                    ');

        $count = (int) $count;
        if ($count) {
            $query->setMaxResults($count);
        }

        return $query->getResult();
    }
}