<?php

namespace Stfalcon\Bundle\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Stfalcon\Bundle\EventBundle\Entity\Options;

/**
 * OptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionsRepository extends EntityRepository
{
    public function getOptions()
    {
        $options = $this->findAll();
        $result = [];
        /** @var Options $option */
        foreach ($options as $option) {
            $result[$option->getName()] = $option->getMean();
        }

        return $result;
    }
}