<?php

namespace Stfalcon\Bundle\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Application\Bundle\UserBundle\Entity\User;
use Stfalcon\Bundle\EventBundle\Entity\Event;
use Stfalcon\Bundle\EventBundle\Entity\Payment;

/**
 * PaymentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
    /**
     * Find tickets of active events for some user
     *
     * @param User $user
     *
     * @return array
     */
    public function findPaidPaymentsForUser(User $user)
    {
        $qb = $this->createQueryBuilder('p');
        $query = $qb->leftJoin('p.tickets', 't')
            ->leftJoin('t.event', 'e')
            ->andWhere('e.useDiscounts = :useDiscounts')
            ->andWhere('t.user = :user')
            ->andWhere('p.status = :status')
            ->setParameter('user', $user)
            ->setParameter('useDiscounts', true)
            ->setParameter('status', Payment::STATUS_PAID)
            ->getQuery();

        return $query->getResult();
    }

    /**
     * @param User  $user
     * @param Event $event
     *
     * @return Payment|null
     */
    public function findPaymentByUserAndEvent(User $user, Event $event)
    {
        $qb = $this->createQueryBuilder('p');
        $query = $qb->leftJoin('p.tickets', 't')
            ->where('t.event = :event')
            ->andWhere('p.user = :user')
            ->setParameter('user', $user)
            ->setParameter('event', $event)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
