<?php

namespace Stfalcon\Bundle\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Stfalcon\Bundle\EventBundle\Entity\Speaker,
    Stfalcon\Bundle\EventBundle\Entity\Event;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository
{
    /**
     * Find reviews of speaker for event
     *
     * @param Speaker $speaker
     * @param Event $event
     *
     * @return array
     */
    public function findReviewsOfSpeakerForEvent(Speaker $speaker, Event $event)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT r
                FROM StfalconEventBundle:Review r
                JOIN r.speakers s
                WHERE
                    s.id = :speakerId
                    AND r.event = :eventId
            ')
            ->setParameters(
                array(
                     'speakerId' => $speaker->getId(),
                     'eventId' => $event->getId()
                )
            )
            ->getArrayResult();
    }
}
