<?php

namespace Stfalcon\Bundle\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Stfalcon\Bundle\EventBundle\Entity\Speaker;
use Stfalcon\Bundle\EventBundle\Entity\Event;

/**
 * ReviewRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository
{
    /**
     * Find reviews of speaker for event.
     *
     * @param Speaker $speaker
     * @param Event   $event
     *
     * @return array
     */
    public function findReviewsOfSpeakerForEvent(Speaker $speaker, Event $event)
    {
        return $this->createQueryBuilder('r')
            ->join('r.speakers', 's')
            ->where('s.id = :speaker')
            ->andWhere('r.event = :event')
            ->setParameter('speaker', $speaker)
            ->setParameter('event', $event)
            ->getQuery()
            ->execute();
    }
}
