<?php

namespace Stfalcon\Bundle\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SpeakerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeakerRepository extends EntityRepository
{
    /**
     * Find speakers for some event
     *
     * @param string $eventSlug
     *
     * @return array
     */
    public function findSpeakersForEvent($eventSlug)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT s
                FROM StfalconEventBundle:Speaker s
                JOIN s.events e
                WHERE e.slug = :eventSlug
            ')
            ->setParameter('eventSlug', $eventSlug)
            ->getResult();
    }
}
