<?php

namespace Stfalcon\Bundle\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Application\Bundle\UserBundle\Entity\User;
use Stfalcon\Bundle\EventBundle\Entity\Event;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{

    /**
     * Find tickets of active events for some user
     *
     * @param User $user
     *
     * @return array
     */
    public function findTicketsOfActiveEventsForUser(User $user)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT t
                FROM StfalconEventBundle:Ticket t
                JOIN t.event e
                WHERE e.active = TRUE
                    AND t.user = :user
            ')
            ->setParameter('user', $user)
            ->getResult();
    }

    /**
     * Find all paid tickets for event
     *
     * @param Event $event
     *
     * @return mixed
     */
    public function findPaidTicketsByEvent(Event $event)
    {
        $query = $this
            ->createQueryBuilder('t')
            ->leftJoin('t.payment', 'p')
            ->andWhere('p.status = :status')
            ->andWhere('t.event = :event')
            ->setParameters(array(
            'event' => $event,
            'status' => \Stfalcon\Bundle\PaymentBundle\Entity\Payment::STATUS_PAID
            ))
            ->getQuery();

        return $query->execute();
    }
}
