#!/bin/bash

usermod -u `stat -c '%u' /app` www-data
chown -R www-data /var/www/

df_info=`df -h|grep '/app'|awk '{print $1}'`
if [ "$df_info" == "osxfs" ]
then
    sudo cp /.macos_conigs/mac_xdebug.ini /etc/php/7.3/mods-available/xdebug.ini
    sudo cp /.macos_conigs/mac_xdebug-cli /usr/local/bin/xdebug-cli
    sudo chmod a+x /usr/local/bin/xdebug-cli
fi

/etc/init.d/php7.3-fpm start
tail -f /var/log/php7.3-fpm.log
