<?php

namespace Stfalcon\Bundle\PaymentsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
}