<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111017011135 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, algorithm VARCHAR(255) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', credentials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL, fullname VARCHAR(255) NOT NULL, company VARCHAR(255) DEFAULT NULL, post VARCHAR(255) DEFAULT NULL, subscribe TINYINT(1) NOT NULL, comment LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_1483A5E992FC23A8 (username_canonical), UNIQUE INDEX UNIQ_1483A5E9A0D96FBF (email_canonical), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pages (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, text LONGTEXT NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE news (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, preview LONGTEXT NOT NULL, text LONGTEXT NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE event__pages (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, text LONGTEXT NOT NULL, INDEX IDX_98D57EBB71F7E88B (event_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE event__speakers (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL, about LONGTEXT NOT NULL, photo VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE event__events_speakers (speaker_id INT NOT NULL, event_id INT NOT NULL, INDEX IDX_873F8739D04A0F27 (speaker_id), INDEX IDX_873F873971F7E88B (event_id), PRIMARY KEY(speaker_id, event_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE event__events (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, about LONGTEXT NOT NULL, logo VARCHAR(255) NOT NULL, active TINYINT(1) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE event__mails (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, text LONGTEXT NOT NULL, start TINYINT(1) DEFAULT NULL, complete TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE event__events_mails (mail_id INT NOT NULL, event_id INT NOT NULL, INDEX IDX_ADE63A26C8776F01 (mail_id), INDEX IDX_ADE63A2671F7E88B (event_id), PRIMARY KEY(mail_id, event_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE event__news (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, preview LONGTEXT NOT NULL, text LONGTEXT NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_1ED586771F7E88B (event_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE event__tickets (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, payment_id INT DEFAULT NULL, user_id INT DEFAULT NULL, status VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_66E2955971F7E88B (event_id), UNIQUE INDEX UNIQ_66E295594C3A3BB (payment_id), UNIQUE INDEX UNIQ_66E29559A76ED395 (user_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE event__reviews (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, text LONGTEXT NOT NULL, INDEX IDX_5BD4E3A271F7E88B (event_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE event__speakers_reviews (review_id INT NOT NULL, speaker_id INT NOT NULL, INDEX IDX_C0C1D68A3E2E969B (review_id), INDEX IDX_C0C1D68AD04A0F27 (speaker_id), PRIMARY KEY(review_id, speaker_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE payments (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, sum NUMERIC(10, 0) NOT NULL, status VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE event__pages ADD CONSTRAINT FK_98D57EBB71F7E88B FOREIGN KEY (event_id) REFERENCES event__events(id)");
        $this->addSql("ALTER TABLE event__events_speakers ADD CONSTRAINT FK_873F8739D04A0F27 FOREIGN KEY (speaker_id) REFERENCES event__speakers(id)");
        $this->addSql("ALTER TABLE event__events_speakers ADD CONSTRAINT FK_873F873971F7E88B FOREIGN KEY (event_id) REFERENCES event__events(id)");
        $this->addSql("ALTER TABLE event__events_mails ADD CONSTRAINT FK_ADE63A26C8776F01 FOREIGN KEY (mail_id) REFERENCES event__mails(id)");
        $this->addSql("ALTER TABLE event__events_mails ADD CONSTRAINT FK_ADE63A2671F7E88B FOREIGN KEY (event_id) REFERENCES event__events(id)");
        $this->addSql("ALTER TABLE event__news ADD CONSTRAINT FK_1ED586771F7E88B FOREIGN KEY (event_id) REFERENCES event__events(id)");
        $this->addSql("ALTER TABLE event__tickets ADD CONSTRAINT FK_66E2955971F7E88B FOREIGN KEY (event_id) REFERENCES event__events(id)");
        $this->addSql("ALTER TABLE event__tickets ADD CONSTRAINT FK_66E295594C3A3BB FOREIGN KEY (payment_id) REFERENCES payments(id)");
        $this->addSql("ALTER TABLE event__tickets ADD CONSTRAINT FK_66E29559A76ED395 FOREIGN KEY (user_id) REFERENCES users(id)");
        $this->addSql("ALTER TABLE event__reviews ADD CONSTRAINT FK_5BD4E3A271F7E88B FOREIGN KEY (event_id) REFERENCES event__events(id)");
        $this->addSql("ALTER TABLE event__speakers_reviews ADD CONSTRAINT FK_C0C1D68A3E2E969B FOREIGN KEY (review_id) REFERENCES event__reviews(id)");
        $this->addSql("ALTER TABLE event__speakers_reviews ADD CONSTRAINT FK_C0C1D68AD04A0F27 FOREIGN KEY (speaker_id) REFERENCES event__speakers(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE event__tickets DROP FOREIGN KEY FK_66E29559A76ED395");
        $this->addSql("ALTER TABLE event__events_speakers DROP FOREIGN KEY FK_873F8739D04A0F27");
        $this->addSql("ALTER TABLE event__speakers_reviews DROP FOREIGN KEY FK_C0C1D68AD04A0F27");
        $this->addSql("ALTER TABLE event__pages DROP FOREIGN KEY FK_98D57EBB71F7E88B");
        $this->addSql("ALTER TABLE event__events_speakers DROP FOREIGN KEY FK_873F873971F7E88B");
        $this->addSql("ALTER TABLE event__events_mails DROP FOREIGN KEY FK_ADE63A2671F7E88B");
        $this->addSql("ALTER TABLE event__news DROP FOREIGN KEY FK_1ED586771F7E88B");
        $this->addSql("ALTER TABLE event__tickets DROP FOREIGN KEY FK_66E2955971F7E88B");
        $this->addSql("ALTER TABLE event__reviews DROP FOREIGN KEY FK_5BD4E3A271F7E88B");
        $this->addSql("ALTER TABLE event__events_mails DROP FOREIGN KEY FK_ADE63A26C8776F01");
        $this->addSql("ALTER TABLE event__speakers_reviews DROP FOREIGN KEY FK_C0C1D68A3E2E969B");
        $this->addSql("ALTER TABLE event__tickets DROP FOREIGN KEY FK_66E295594C3A3BB");
        $this->addSql("DROP TABLE users");
        $this->addSql("DROP TABLE pages");
        $this->addSql("DROP TABLE news");
        $this->addSql("DROP TABLE event__pages");
        $this->addSql("DROP TABLE event__speakers");
        $this->addSql("DROP TABLE event__events_speakers");
        $this->addSql("DROP TABLE event__events");
        $this->addSql("DROP TABLE event__mails");
        $this->addSql("DROP TABLE event__events_mails");
        $this->addSql("DROP TABLE event__news");
        $this->addSql("DROP TABLE event__tickets");
        $this->addSql("DROP TABLE event__reviews");
        $this->addSql("DROP TABLE event__speakers_reviews");
        $this->addSql("DROP TABLE payments");
    }
}
