<?php

namespace Application\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111103110908 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE event__events_mails");
        $this->addSql("ALTER TABLE event__mails ADD event_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE event__mails ADD CONSTRAINT FK_DBF9BBCB71F7E88B FOREIGN KEY (event_id) REFERENCES event__events(id) ON UPDATE CASCADE ON DELETE CASCADE");
        $this->addSql("CREATE INDEX IDX_DBF9BBCB71F7E88B ON event__mails (event_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE event__events_mails (mail_id INT NOT NULL, event_id INT NOT NULL, INDEX IDX_ADE63A26C8776F01 (mail_id), INDEX IDX_ADE63A2671F7E88B (event_id), PRIMARY KEY(mail_id, event_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE event__events_mails ADD CONSTRAINT FK_ADE63A2671F7E88B FOREIGN KEY (event_id) REFERENCES event__events(id)");
        $this->addSql("ALTER TABLE event__events_mails ADD CONSTRAINT FK_ADE63A26C8776F01 FOREIGN KEY (mail_id) REFERENCES event__mails(id)");
        $this->addSql("ALTER TABLE event__mails DROP FOREIGN KEY FK_DBF9BBCB71F7E88B");
        $this->addSql("DROP INDEX IDX_DBF9BBCB71F7E88B ON event__mails");
        $this->addSql("ALTER TABLE event__mails DROP event_id");
    }
}
