<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121015121524 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE payments ADD has_discount TINYINT(1) NOT NULL");
        $this->addSql("ALTER TABLE payments ADD amount_without_discount NUMERIC(10, 2) NOT NULL");
        // Все существующие платежы проходили без скидок
        $this->addSql("UPDATE payments SET has_discount = FALSE");
        // У всех предыдущих платежей сумма без скидки равняется сумме к оплате
        $this->addSql("UPDATE payments SET amount_without_discount = amount");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE payments DROP has_discount");
        $this->addSql("ALTER TABLE payments DROP amount_without_discount");
    }
}
