<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111023202940 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE payments ADD created_at DATETIME NOT NULL, ADD updated_at DATETIME NOT NULL");
        $this->addSql("ALTER TABLE payments CHANGE sum amount NUMERIC(10, 0) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE payments CHANGE amount sum NUMERIC(10, 0) NOT NULL");
        $this->addSql("ALTER TABLE payments DROP created_at, DROP updated_at");
    }
}
