sentry:
    dsn: "%env(SENTRY_DSN)%"
    options:
        environment: "%env(APP_ENV)%"
        send_default_pii: true
        excluded_exceptions:
            - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
            - 'Symfony\Component\HttpKernel\Exception\BadRequestHttpException'
            - 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException'
            - 'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException'
            - 'Symfony\Component\Security\Core\Exception\AccessDeniedException'
            - 'App\Exception\NeedUserDataException'