#!/bin/bash

sed -i s/%fwdays_web_server_name%/$SERVER_NAME/ /etc/nginx/conf.d/fwdays.conf
echo -e "$PARAMETERS" > /app/config/parameters.ini
/etc/init.d/php7.1-fpm start
/etc/init.d/nginx start

tail -f /var/log/nginx/access.log
