parameters:
    locale: uk
    locales:
        - uk
        - en

    interkassa_override_callbacks: '%env(INTERKASSA_OVERRIDE_CALLBACKS)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $locale: '%locale%'
            $locales: '%locales%'
            $projectDir: '%kernel.project_dir%'
            $googleApiKey: '%env(GOOGLE_API_KEY)%'
            $appConfig: '%app.config%'
            $localeCookieName: '%jms_i18n_routing.cookie.name%'
            $environment: '%env(APP_ENV)%'
            $oAuthUserProviderProperties: {facebook: facebookID, google: googleID}
            $paymentSystem: '@App\Service\PaymentProcess\InterkassaService'
            $isOverrideCallbacks: '%env(INTERKASSA_OVERRIDE_CALLBACKS)%'

    fos_user.registration.controller:
        class: App\Controller\RegistrationController
        public: true
        arguments:
            - '@event_dispatcher'
            - '@fos_user.registration.form.factory'
            - '@fos_user.user_manager'
            - '@security.token_storage'
            - '@fos_user.security.login_manager'
            - '@App\Handler\LoginHandler'
        calls:
            - [setContainer, ["@service_container"]]

    App\:
        resource: '../src/{Command,EventListener,Form,Helper,Repository,Security,Serializer,Service,Twig,Validator}/'

    App\Controller\:
        resource: '../src/Controller/'
        tags:
            - 'controller.service_arguments'

#    monolog.processor.added_host:
#        class: Monolog\Processor\WebProcessor
#        tags:
#            - { name: monolog.processor, method: __invoke }

    App\DataFixtures\PrepareFileStorage:
        arguments:
            - '%kernel.environment%'
            -
                - '@oneup_flysystem.sponsor_image_filesystem'
                - '@oneup_flysystem.speaker_photo_filesystem'
                - '@oneup_flysystem.event_image_filesystem'
                - '@oneup_flysystem.upload_image_filesystem'

#    App\Twig\AppPluralizationExtension:
#        tags:
#            - { name: twig.extension}

#    App\Service\UrlForRedirect:
#        arguments: ["@router", "%locales%"]

#    App\Service\Ticket\WaitPaymentReceiveEventState:
#        calls: [[setTranslator, ['@translator']]]
#    App\Service\Ticket\DoneEventState:
#        calls: [[setTranslator, ['@translator']]]
#    App\Service\Ticket\SaleOpenEventState:
#        arguments: ['@router']
#        calls: [[setTranslator, ['@translator']]]
#    App\Service\Ticket\SoldOutEventState:
#        calls: [[setTranslator, ['@translator']]]
#    App\Service\Ticket\WannaVisitEventState:
#        calls: [[setTranslator, ['@translator']]]

    App\Service\Ticket\TicketService:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%app.config%'
            - '@translator'
            - '@router'
            - '@App\Service\User\UserService'
        calls:
            - [addEventState, ['@App\Service\Ticket\DoneEventState']]
            - [addEventState, ['@App\Service\Ticket\WannaVisitEventState']]
            - [addEventState, ['@App\Service\Ticket\SoldOutEventState']]
            - [addEventState, ['@App\Service\Ticket\SaleOpenEventState']]

#    App\Twig\AppDateTimeExtension:
#        arguments:
#            - '@sonata.intl.twig.extension.datetime'
#            - '@translator'
#        tags:
#            - { name: twig.extension}

#    App\Twig\AssetVersionExtension:
#        arguments: ["%kernel.root_dir%", "%kernel.environment%"]
#        tags:
#            - { name: twig.extension }

#    App\EventListener\ExceptionListener:
#        arguments: ["@session"]
#        calls:
#            - [setRouter, ['@router']]
#        tags:
#            - { name: kernel.event_listener, event: kernel.exception }

#    App\Helper\NewPdfGeneratorHelper:
#        arguments:
#            - '@twig'
#            - '@router'
#            - '@Endroid\QrCode\QrCode'
#            - '@kernel'
#            - '@App\Service\SvgToJpg'
#            - '@oneup_flysystem.event_image_filesystem'
#            - '@vich_uploader.property_mapping_factory'

#    App\Service\SvgToJpg:
#        arguments:
#            - "@monolog.logger"

#    App\Service\MyMailer:
#        arguments: ['@swiftmailer.transport']

#    App\EventListener\PromoCodeRequestListener:
#        arguments:
#            - '@router'
#            - '@session'
#        tags:
#            - { name: kernel.event_listener, event: kernel.request }

#    App\Service\GoogleMapService:
#        arguments: ['%google_api_key%', '@http_client']

#    App\Service\PaymentProcess\WayForPayService:
#        arguments:
#            - '%app.config%'
#            - '@translator'
#            - '@request_stack'
#            - '@router'
#            - '@security.token_storage'
#            - '@doctrine.orm.entity_manager'
#            - '@logger'
#            - '@App\Service\ReferralService'
#            - '@session'

#    App\Service\PaymentProcess\InterkassaService:
#        arguments:
#            - "%app.config%"
#            - "@translator"
#            - "@request_stack"
#            - '@router'
#            - '@doctrine.orm.entity_manager'
#            - '@logger'
#            - '@App\Service\ReferralService'
#            - '@session'
#            - '%interkassa_override_callbacks%'

#    App\Service\EventService:
#        arguments:
#            - '@app.event.repository.service'
#            - '@app.ticket_cost_repository.service'
#            - '@app.event_review.repository.service'
#            - '@security.authorization_checker'

#    App\Service\ChartService: ~

#    App\Service\AnalyticsService:
#        arguments: ["@doctrine.orm.entity_manager"]

#    App\EventListener\LoginEntryPoint:
#        arguments: ["@jms_i18n_routing.router"]

    App\Handler\LoginHandler: ~
#    App\Handler\LoginHandler:
#        arguments:
#            - '@router'
#            - '@App\Service\ReferralService'
#            - '@fos_user.user_manager'
#            - '@App\Service\UrlForRedirect'

#    App\Security\OAuthUserProvider:
#        arguments:
#            - "@fos_user.user_manager"
#            - {facebook: facebookID, google: googleID}
#            - "@service_container"

#    App\Service\PaymentService:
#        arguments:
#            - '@doctrine.orm.entity_manager'
#            - '@App\Service\Ticket\TicketService'
#            - '@translator'
#            - '@App\Service\User\UserService'
#            - '@App\Service\ReferralService'
#            - '@session'

#    App\Service\ReferralService:
#        arguments: ['@service_container']


    App\Menu\MenuBuilder:
        arguments: ['@knp_menu.factory','%locales%', '@mobile_detect.mobile_detector']

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

#    App\EventListener\LocaleUrlResponseListener:
#        tags:
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 128 }
#            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 128 }
#        arguments:
#            - '%jms_i18n_routing.default_locale%'
#            - '%jms_i18n_routing.locales%'
#            - '%jms_i18n_routing.cookie.name%'
#            - '@router'
#            - '@maxmind.geoip'
#
#    App\Service\LocalsRequiredService:
#        arguments: ['%jms_i18n_routing.default_locale%', '%jms_i18n_routing.locales%']

    App\Command\AppResolveLiipCacheCommand:
        calls:
            - [setContainer, ['@service_container']]

    App\Command\StfalconChangeTranslationCommand:
        calls:
            - [setContainer, ['@service_container']]

    App\Command\StfalconRecalculateTicketSoldCountCommand:
        calls:
            - [setContainer, ['@service_container']]

    App\Command\StfalconMailerCommand:
        calls:
            - [setContainer, ['@service_container']]

    #    sonata.admin.menu.matcher.voter.children:
    #        class: Sonata\AdminBundle\Menu\Matcher\Voter\ChildrenVoter
    #        arguments: ['@knp_menu.matcher']

#    vich_uploader.my_storage.flysystem:
#        class: App\Service\MyFlySystemStorage
#        arguments: ['@vich_uploader.property_mapping_factory', '@oneup_flysystem.mount_manager']

    liip_imagine.cache.resolver.prototype.flysystem:
        class: App\Service\MyFlySystemResolver
        arguments: ['', '@router.request_context', '', '', '']

    Endroid\QrCode\QrCode: ~
    App\Service\PaymentProcess\InterkassaService: ~
    App\Service\PaymentProcess\WayForPayService: ~

#    App\Helper\MailerHelper:
#        arguments:
#            - '@twig'
#            - '@doctrine.orm.entity_manager'
#            - '@router'
#            - '@mailer'
#            - "@translator"

#    App\EventListener\PaymentListener:
#        tags:
#            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
#        arguments: ['@service_container']

    app.menu.main.redesign:
        class: Knp\Menu\MenuItem
        tags:
            - { name: knp_menu.menu, alias: main_redesign }
        factory: ['@App\Menu\MenuBuilder', createMainMenuRedesign]
        arguments: ['@request_stack']

    app.menu.main.login.redesign:
        class: Knp\Menu\MenuItem
        tags:
            - { name: knp_menu.menu, alias: login_redesign }
        factory: ['@App\Menu\MenuBuilder', createLoginMenu]
        arguments: ['@request_stack']

    App\Model\UserManager: ~
#    App\Model\UserManager:
#        arguments:
#            - '@fos_user.util.password_updater'
#            - '@fos_user.util.canonical_fields_updater'
#            - '@fos_user.object_manager'
#            - '%fos_user.model.user.class%'
#            - '@validator'
#            - '@App\Helper\MailerHelper'
#            - '@session'

    App\Form\Type\ProfileFormType:
        arguments:
            - "%locales%"
        tags:
            - { name: form.type, alias: application_profile }

    App\Form\Type\RegistrationFormType:
        arguments:
            - "%locales%"
        tags:
            - { name: form.type, alias: application_registration }

#    App\Serializer\Normalizer\PaymentNormalizer:
#        arguments: ['@translator', '@serializer.normalizer.object']
#        tags:
#            - { name: serializer.normalizer }

#    App\Serializer\Normalizer\TicketNormalizer:
#        arguments: ['@translator', '@serializer.normalizer.object', '%app.config%']
#        tags:
#            - { name: serializer.normalizer }

#    App\Service\EmailHashValidationService: ~

#    App\Service\TranslatedMailService:
#        arguments: ['%locale%']

#    App\Service\User\UserService:
#        calls:
#            - [setTokenStorage, ['@security.token_storage']]

    Symfony\Bundle\FrameworkBundle\Routing\Router: '@router'
    Symfony\Component\HttpFoundation\Session\Session: '@session'
    Symfony\Component\Security\Core\Authorization\AuthorizationChecker: '@security.authorization_checker'
    Maxmind\Bundle\GeoipBundle\Service\GeoipManager: '@maxmind.geoip'
    League\Flysystem\MountManager: '@oneup_flysystem.mount_manager'
    Sonata\IntlBundle\Twig\Extension\DateTimeExtension: '@sonata.intl.twig.extension.datetime'
    Monolog\Logger: '@logger'
    Doctrine\Common\Persistence\ObjectManager: '@fos_user.object_manager'
    Doctrine\ORM\EntityManager: '@doctrine.orm.entity_manager'
    FOS\UserBundle\Form\Factory\FactoryInterface: '@fos_user.registration.form.factory'
    FOS\UserBundle\Security\LoginManager: '@fos_user.security.login_manager'
    Symfony\Contracts\HttpClient\HttpClientInterface:
        factory: ['Symfony\Component\HttpClient\HttpClient', 'create']