<?php

namespace Stfalcon\Bundle\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
//    public function getAllNews()
//    {
//        $query = $this->_em->createNativeQuery('SELECT * FROM news UNION  WHERE name = ?', $rsm);
//        $query->setParameter(1, 'romanb');
//        echo 111;
//        exit;
//    }
}