<?php

namespace Stfalcon\Bundle\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Stfalcon\Bundle\EventBundle\Entity\Event;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{

   /**
     * Get array of last news for event
     * 
     * @param integer $count
     * @return array
     */
    public function getLastNewsForEvent(Event $event, $count)
    {
        $count = (int) $count;
        if (!$count) {
            throw new Exception('You must set the count of the latest news');
        }
        
        $query = $this->getEntityManager()
                ->createQuery('
                    SELECT 
                        n
                    FROM 
                        StfalconEventBundle:News n
                    WHERE 
                        n.event = :event
                    ORDER BY 
                        n.created_at DESC
                    ')
                ->setParameter('event', $event)
                ->setMaxResults($count);
        
        return $query->getResult();
    }
    
}