<?php

namespace Stfalcon\Bundle\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Stfalcon\Bundle\EventBundle\Entity\Event;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{

    private function _getBaseQueryBuilder($count = null)
    {
        $qb = $this->getEntityManager()
                ->createQueryBuilder()
                ->add('select', 'n')
                ->add('from', 'StfalconEventBundle:News n')
                ->add('orderBy', 'n.created_at DESC');

        $count = (int) $count;
        if ($count) {
            $qb->setMaxResults($count);
        }

        return $qb;
    }
    
    /**
     * Get array of last news
     * 
     * @param integer $count
     * @return array
     */
    public function getLastNews($count = null)
    {
        return $this->_getBaseQueryBuilder($count)->getQuery()->getResult();
    }
    
    /**
     * Get array of last news for event
     * 
     * @param integer $count
     * @return array
     */
    public function getLastNewsForEvent(Event $event, $count = null)
    {
        $qb = $this->_getBaseQueryBuilder($count)
                ->where('n.event = :event')
                ->setParameter('event', $event);
        
        return $qb->getQuery()->getResult();
    }
    
}