<?php

namespace Stfalcon\Bundle\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{

    /**
     * @return array
     */
    public function findAllPaid()
    {
        $qb = $this->getEntityManager()
                ->createQueryBuilder()
                ->add('select', 't')
                ->add('from', 'StfalconEventBundle:Ticket t')
                ->where('t.status = :status')
                ->setParameter('status', 'paid')
                ->add('orderBy', 't.status DESC');

        return $qb->getQuery()->getResult();
    }
}