services:

    fos_user.registration.controller:
        class: App\Controller\RegistrationController
        public: true
        arguments:
            - "@event_dispatcher"
            - "@fos_user.registration.form.factory"
            - "@fos_user.user_manager"
            - "@security.token_storage"

        calls:
            - [setContainer, ["@service_container"]]
