services:

    app.admin.event_audience:
        class: Application\Bundle\DefaultBundle\Admin\EventAudienceAdmin
        arguments: [~, Application\Bundle\DefaultBundle\Entity\EventAudience, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: События, label: Аудитории}

    app.admin.event_sponsor:
        class: Application\Bundle\DefaultBundle\Admin\EventSponsorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        arguments: ['', 'Application\Bundle\DefaultBundle\Entity\EventSponsor', ~]

    app.admin.sponsor:
        class: Application\Bundle\DefaultBundle\Admin\SponsorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Спонсоры, label: Спонсоры }
        arguments: ['', 'Application\Bundle\DefaultBundle\Entity\Sponsor', ~]

    app.admin.category:
        class: Application\Bundle\DefaultBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Спонсоры, label: Категории }
        arguments: ['', 'Application\Bundle\DefaultBundle\Entity\Category', ~]

    app.admin.event:
        class: Application\Bundle\DefaultBundle\Admin\EventAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: События, label: События }
        arguments: ['', 'Application\Bundle\DefaultBundle\Entity\Event', ~]

    app.admin.event_group:
        class: Application\Bundle\DefaultBundle\Admin\EventGroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: События, label: Групы }
        arguments: ['', Application\Bundle\DefaultBundle\Entity\EventGroup, '']

    app.admin.review:
        class: Application\Bundle\DefaultBundle\Admin\ReviewAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: События, label: Доклады }
        arguments: ['', 'Application\Bundle\DefaultBundle\Entity\Review', ~]
    app.admin.speaker:
        class: Application\Bundle\DefaultBundle\Admin\SpeakerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: События, label: Докладчики }
        arguments: ['', 'Application\Bundle\DefaultBundle\Entity\Speaker', ~]

    app.admin.event_page:
        class: Application\Bundle\DefaultBundle\Admin\EventPageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: События, label: Страницы }
        arguments: ['', 'Application\Bundle\DefaultBundle\Entity\EventPage', ~]

    app.admin.mail:
        class: Application\Bundle\DefaultBundle\Admin\MailAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Рассылки, label: Рассылки }
        arguments: ['', 'Application\Bundle\DefaultBundle\Entity\Mail', 'ApplicationDefaultBundle:MailAdmin']
        calls:
            - [addChild, ['@app.admin.mail_queue']]

    app.admin.mail_queue:
        class: Application\Bundle\DefaultBundle\Admin\MailQueueAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Рассылки, label: Очередь }
        arguments: ['', 'Application\Bundle\DefaultBundle\Entity\MailQueue', ~]

    app.admin.ticket:
        class: Application\Bundle\DefaultBundle\Admin\TicketAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Билеты, label: Билеты }
        arguments: ['', 'Application\Bundle\DefaultBundle\Entity\Ticket', 'ApplicationDefaultBundle:TicketCRUD']

    app.admin.payment:
        class: Application\Bundle\DefaultBundle\Admin\PaymentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Билеты, label: Платежи }
        arguments: ['', 'Application\Bundle\DefaultBundle\Entity\Payment', ~]

    app.admin.promo_code:
        class: Application\Bundle\DefaultBundle\Admin\PromoCodeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Билеты, label: 'Промо коды' }
        arguments: ['', 'Application\Bundle\DefaultBundle\Entity\PromoCode', ~]

    app.admin.user:
        class: Application\Bundle\DefaultBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Пользователи, label: 'Пользователи' }
        arguments: ['', Application\Bundle\DefaultBundle\Entity\User, ~]

    app.admin.page:
        class: Application\Bundle\DefaultBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Страницы, label: Страницы }
        arguments: ['', 'Application\Bundle\DefaultBundle\Entity\Page', ~]

    app.admin.ticket_cost:
        class: Application\Bundle\DefaultBundle\Admin\TicketCostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false}
        arguments: [~, 'Application\Bundle\DefaultBundle\Entity\TicketCost', ~]

    app.admin.event_block:
        class: Application\Bundle\DefaultBundle\Admin\EventBlockAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false}
        arguments: [~, Application\Bundle\DefaultBundle\Entity\EventBlock, ~]

    app.admin.wayforpay_log:
        class: Application\Bundle\DefaultBundle\Admin\WayForPayLogAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Логи, label: Логи wayforpay}
        arguments: [~, 'Application\Bundle\DefaultBundle\Entity\WayForPayLog', ~]
