<?php

namespace DoctrineMigrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111103095337 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE event__pages ADD show_in_menu TINYINT(1) NOT NULL");
        $this->addSql("ALTER TABLE event__mails CHANGE start start TINYINT(1) NOT NULL, CHANGE complete complete TINYINT(1) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE event__mails CHANGE start start TINYINT(1) DEFAULT NULL, CHANGE complete complete TINYINT(1) DEFAULT NULL");
        $this->addSql("ALTER TABLE event__pages DROP show_in_menu");
    }
}
