FROM gitlab.stfalcon.com:4567/stfalcon/fwdays/fwdays-dev:v1
COPY sonar-scanner-3.3.0.1492-linux.tar.gz /sonar-scanner-3.3.0.1492-linux.tar.gz
RUN sudo tar -xvf /sonar-scanner-3.3.0.1492-linux.tar.gz -C /
