#!/bin/bash

sed -i s/app.php/app_dev.php/ /var/www/html/web/.htaccess
cp /var/www/html/docker-files/app_dev_docker.php /var/www/html/web/app_dev.php
cp /var/www/html/app/config/parameters.ini.docker /var/www/html/app/config/parameters.ini
cd /var/www/html && curl -s https://getcomposer.org/installer | php
cd /var/www/html && ./composer.phar install

/etc/init.d/apache2 start

./console doctrine:database:create
./console doctrine:migrations:migrate

./console assets:install web --symlink
./console lexik:translations:import

chmod -R 777 /var/www/html/app/cache
chmod -R 777 /var/www/html/app/logs

mkdir /var/www/html/web/tmp/media
mkdir /var/www/html/web/tmp/media/cache
chmod -R 777 /var/www/html/web/tmp/media/cache

mkdir /var/www/html/web/uploads/sponsors
mkdir /var/www/html/web/uploads/speakers
mkdir /var/www/html/web/uploads/events
chmod -R 777 /var/www/html/web/uploads
chmod -R 777 /var/www/html/app/sessions

./console doctrine:fixtures:load

cd / && wget https://nodejs.org/dist/v6.11.3/node-v6.11.3-linux-x64.tar.xz
cd / && tar -xvf node-v6.11.3-linux-x64.tar.xz
cp -a /node-v6.11.3-linux-x64/* /
npm install -g gulp
cd /var/www/html && npm install
cd /var/www/html && npm run gulp-dev

while true; do sleep 10000; done
