#!/bin/bash

sed -i s/app.php/app_dev.php/ /var/www/html/web/.htaccess
cp /var/www/html/docker-files/app_dev_docker.php /var/www/html/web/app_dev.php
cp /var/www/html/app/config/parameters.ini.docker /var/www/html/app/config/parameters.ini
cd /var/www/html && curl -s https://getcomposer.org/installer | php
cd /var/www/html && ./composer.phar install

/etc/init.d/apache2 start

./console doctrine:database:create
./console doctrine:migrations:migrate
./console doctrine:fixtures:load
./console assets:install web --symlink

chmod -R 777 /var/www/html/app/cache
chmod -R 777 /var/www/html/app/logs

mkdir /var/www/html/web/tmp/media
mkdir /var/www/html/web/tmp/media/cache
chmod -R 777 /var/www/html/web/tmp/media/cache

mkdir /var/www/html/web/uploads/sponsors
mkdir /var/www/html/web/uploads/speakers
mkdir /var/www/html/web/uploads/events
chmod -R 777 /var/www/html/web/uploads

chmod -R 777 /var/www/html/app/sessions

while true; do sleep 10000; done
