apiVersion: v1
kind: Service
metadata:
  name: fwdays-smtp
  namespace: fwdays-stag
  labels:
    app: fwdays-smtp
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8025
  - name: smtp
    protocol: TCP
    port: 25
    targetPort: 1025
  selector:
    app: fwdays-smtp
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: fwdays-smtp
  namespace: fwdays-stag
  labels:
    app: fwdays-smtp
spec:
  selector:
    matchLabels:
      app: fwdays-smtp
  template:
    metadata:
      labels:
        app: fwdays-smtp
    spec:
      containers:
      - name: fwdays-smtp
        image: mailhog/mailhog
        ports:
        - containerPort: 1025
          name: smtp
        - containerPort: 8025
          name: http
        name: fwdays-smtp
