<?php

namespace Application\Bundle\DefaultBundle\Repository;

use Application\Bundle\DefaultBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Application\Bundle\DefaultBundle\Entity\Event;
use Application\Bundle\DefaultBundle\Entity\EventGroup;

/**
 * EventRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    /**
     * @param User   $user
     * @param bool   $active
     * @param string $sort
     *
     * @return array
     */
    public function getSortedUserWannaVisitEventsByActive(User $user, $active = true, $sort = 'ASC')
    {
        $qb = $this->createQueryBuilder('e');
        $qb
            ->join('Application\Bundle\DefaultBundle\Entity\User', 'u', 'WITH', $qb->expr()->eq('u.id', ':user_id'))
            ->join('u.wantsToVisitEvents', 'wve', 'WITH', $qb->expr()->eq('e.id', 'wve.id'))
            ->where($qb->expr()->eq('e.active', ':active'))
            ->setParameters(['user_id' => $user, 'active' => $active])
            ->orderBy('e.date', $sort);

        return $qb->getQuery()->getResult();
    }

    /**
     * @param EventGroup $eventGroup
     *
     * @return null|Event
     */
    public function findFutureEventFromSameGroup(EventGroup $eventGroup)
    {
        $qb = $this->createQueryBuilder('e');
        $qb
            ->where($qb->expr()->eq('e.active', ':active'))
            ->andWhere($qb->expr()->gte('e.date', ':date'))
            ->andWhere($qb->expr()->eq('e.group', ':group'))
            ->setParameters([
                'active' => true,
                'group' => $eventGroup,
                'date' => new \DateTime(),
            ])
            ->orderBy('e.date', 'ASC')
            ->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param int $count
     *
     * @return Event[]
     */
    public function findClosesActiveEvents($count)
    {
        $qb = $this->createQueryBuilder('e');
        $qb
            ->where($qb->expr()->eq('e.active', ':active'))
            ->andWhere($qb->expr()->gte('e.date', ':date'))
            ->setParameters([
                'active' => true,
                'date' => new \DateTime(),
            ])
            ->orderBy('e.date', 'ASC')
            ->setMaxResults($count);

        return $qb->getQuery()->getResult();
    }
}
