<?php

namespace Application\Bundle\DefaultBundle\Repository;

use Application\Bundle\DefaultBundle\Entity\Event;
use Doctrine\ORM\EntityRepository;

/**
 * SponsorRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsorRepository extends EntityRepository
{
    /**
     * Get all sponsors of event with category.
     *
     * @param Event $event
     *
     * @return array List of sponsors
     */
    public function getSponsorsOfEventWithCategory(Event $event)
    {
        $qb = $this->createQueryBuilder('s');

        $qb->select('s', 'c.id')
            ->where($qb->expr()->eq('e.id', ':eventId'))
            ->join('s.sponsorEvents', 'se')
            ->join('se.event', 'e')
            ->join('se.category', 'c')
            ->setParameter('eventId', $event->getId())
            ->orderBy('c.sortOrder', 'DESC')
            ->orderBy('s.sortOrder', 'DESC')
        ;

        return $qb->getQuery()->getResult();
    }
}
