oneup_flysystem:
    adapters:
        sponsor_image_adapter:
            awss3v3:
                client: 'app.assets.s3'
                bucket: '%aws_s3_bucketname%'
                prefix: '%kernel.environment%%app.sponsor_image%'
        speaker_photo_adapter:
            awss3v3:
                client: 'app.assets.s3'
                bucket: '%aws_s3_bucketname%'
                prefix: '%kernel.environment%%app.speaker_image%'
        event_image_adapter:
            awss3v3:
                client: 'app.assets.s3'
                bucket: '%aws_s3_bucketname%'
                prefix: '%kernel.environment%%app.event_image%'

    filesystems:
        sponsor_image:
            adapter: 'sponsor_image_adapter'
            mount: 'sponsor_image'
        speaker_photo:
            adapter: 'speaker_photo_adapter'
            mount: 'speaker_photo'
        event_image:
            adapter: 'event_image_adapter'
            mount: 'event_image'
